### ISSUE TITLE
Want to join the organization.

### ISSUE THREAD

**Issue by lionelsamrat10** [Py-Contributors/Getting-Started#6]

**Comment by codeperfectplus** [comment]
HI @lionelsamrat10,

This Github Organization was created to support open-source developement. some projects are moved to different account due to inactivity in org.

If you are intrested please check these 3 open source project which are still active.

1. Discord Bot to manage server and some fun api for user. adding more tools to make it more useful.
https://github.com/Cybelbot

2. Collection of useful python scripts. adding more scripts to ease the tasks.
https://github.com/codePerfectPlus/awesomeScripts/

3. Algorithms and Data Strucuture in PYthon/C++.
https://github.com/codePerfectPlus/AlgorithmsAndDataStructure

4. Object detection conversion tool
https://github.com/codePerfectPlus/dataset-convertor

Happy coding
