### ISSUE TITLE
Let me join to your organization

### ISSUE THREAD

**Issue by thuongtruong1009** [Py-Contributors/Getting-Started#7]
Hi guys!
I want to join your organization to learn more and more about open-source code.
Thank you very much!

**Comment by codeperfectplus** [comment]
HI @thuongtruong1009, 

This Github Organization was created to support open-source developement. some projects are moved to different account due to inactivity in org.

If you are intrested please check these 3 open source project which are still active.

1. Discord Bot to manage server and some fun api for user. adding more tools to make it more useful.
https://github.com/Py-Contributors/cybel 

2. Collection of useful python scripts. adding more scripts to ease the tasks.
https://github.com/codePerfectPlus/awesomeScripts/

3. Algorithms and Data Strucuture in PYthon/C++.
https://github.com/codePerfectPlus/AlgorithmsAndDataStructure

Happy coding

**Comment by thuongtruong1009** [comment]
Thank you very much, I am learning about this.
